In [1]:
from data import *

from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

from sklearn.impute import SimpleImputer

/Users/lilimatic/opt/anaconda3/lib/python3.8/site-packages/pandas/core/computation/expressions.py:20: UserWarning: Pandas requires version '2.7.3' or newer of 'numexpr' (version '2.7.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [30]:
#Read data

df, X, y, X_train, X_test, y_train, y_test = dataset('full',28,99,'mixed',0.25,'none')

In [31]:
g = 'Gastrointestinal.Bleed.since.the.last.visit.Gastrointestinal.bleed...and.Choose..Treatment.Day.7..'
df[g]  = df[g].astype('Int64') 
imp    = SimpleImputer(strategy="most_frequent")
df[g]  = imp.fit_transform(df[g].values.reshape(-1, 1))
df[g]  = df[g].astype('Int64')

In [32]:
#Single MODE-IMPUTATION on only variable with missing values

s = ['Hepatic.Encephalopathy...Merged','Hepatic.Encephalopathy...Treatment.Day.7..']
df[s] = df[s].astype('Int64')
imp = SimpleImputer(strategy="most_frequent")
for x in s:
    df[x] = imp.fit_transform(df[x].values.reshape(-1, 1))
    df[x] = df[x].astype('Int64')

In [33]:
df['Hepatic.Encephalopathy...Treatment.Day.7..'].dtypes == 'Int64'

True

In [34]:
cat_var = [x for x in df if (df[x].dtypes  == 'Int64' or df[x].dtypes  == 'int64') ]

In [35]:
df[cat_var] = df[cat_var].astype('Int64')

In [36]:
cat_var
#Sanity check
#df[cat_var].isnull().sum()

['Hepatic.Encephalopathy...Treatment.Day.7..',
 'Day.7.infection',
 'Gastrointestinal.Bleed.since.the.last.visit.Gastrointestinal.bleed...and.Choose..Treatment.Day.7..',
 'Gender',
 'Baseline_sepsis',
 'Baseline_GIB',
 'Hepatic.Encephalopathy...Merged',
 'Prednisolone',
 'D28_DTH']

In [37]:
num_var = list(set(list(df.columns)) - set(cat_var))

In [38]:
mice = IterativeImputer(max_iter=10, random_state=0)

In [39]:
imputed_values = pd.DataFrame(mice.fit_transform(df), columns=df.columns)

/Users/lilimatic/opt/anaconda3/lib/python3.8/site-packages/sklearn/impute/_iterative.py:800: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(

In [29]:
imputed_values

,Hepatic.Encephalopathy...Treatment.Day.7..,Day.7.infection,Gastrointestinal.Bleed.since.the.last.visit.Gastrointestinal.bleed...and.Choose..Treatment.Day.7..,Temperature..Treatment.Day.7..,Pulse..Treatment.Day.7..,Systolic.BP..Treatment.Day.7..,Diastolic.BP..Treatment.Day.7..,MAP..Treatment.Day.7,Hb..1.decimal.point..Haematology..Treatment.Day.7..,Platelets.day.7,...,bDNA,Ferritin_ngml,Iron_mumoll,Transferrin,TSAT,PNPLA3_Add,PNPLA3_Rec,HPCT_NG,Prednisolone,D28_DTH
0,1.0,0.0,0.0,36.8000,86.000000,135.000000,74.000000,94.333333,110.000000,92.000000,...,18.110645,1325.4,9.3,57.0,63.8,0.0,0.0,0.916418,0.0,0.0
1,1.0,0.0,0.0,36.1000,75.000000,110.000000,72.000000,84.666667,122.000000,107.000000,...,5.703739,5598.0,17.4,81.0,84.6,0.0,0.0,0.261571,1.0,0.0
2,0.0,0.0,0.0,37.5000,91.000000,102.000000,62.000000,75.333333,74.000000,218.000000,...,27.647067,3675.0,19.2,78.0,97.9,0.0,0.0,0.173867,0.0,0.0
3,0.0,0.0,0.0,36.5000,87.000000,133.000000,68.000000,89.666667,85.000000,77.000000,...,5.821736,8661.0,11.7,144.0,32.2,1.0,0.0,0.146488,0.0,0.0
4,0.0,0.0,0.0,36.6335,89.470684,114.951049,67.604196,83.386480,98.225555,182.927347,...,4.709972,1832.1,26.4,123.0,85.3,2.0,1.0,0.204013,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1063,1.0,0.0,0.0,37.1000,75.000000,117.000000,77.000000,90.333333,97.000000,126.000000,...,0.803096,196.2,18.0,174.0,41.0,2.0,1.0,0.486696,0.0,0.0
1064,0.0,0.0,0.0,36.4000,84.000000,126.000000,81.000000,96.000000,97.000000,119.000000,...,3.522411,1807.8,33.9,141.0,95.2,1.0,0.0,0.990790,0.0,0.0
1065,0.0,0.0,0.0,37.5000,70.000000,100.000000,62.000000,74.666667,119.000000,366.000000,...,4.197820,396.6,12.0,72.0,66.8,1.0,0.0,1.199673,1.0,0.0
1066,0.0,0.0,0.0,36.8000,120.000000,134.000000,75.000000,94.666667,106.000000,160.000000,...,15.325191,352.5,17.7,129.0,54.6,0.0,0.0,0.827577,1.0,0.0
1067,1.0,1.0,0.0,36.4000,100.000000,103.000000,70.000000,81.000000,106.000000,77.000000,...,164.279243,10185.0,9.9,45.0,87.9,0.0,0.0,0.000000,0.0,0.0

In [40]:
df

,Hepatic.Encephalopathy...Treatment.Day.7..,Day.7.infection,Gastrointestinal.Bleed.since.the.last.visit.Gastrointestinal.bleed...and.Choose..Treatment.Day.7..,Temperature..Treatment.Day.7..,Pulse..Treatment.Day.7..,Systolic.BP..Treatment.Day.7..,Diastolic.BP..Treatment.Day.7..,MAP..Treatment.Day.7,Hb..1.decimal.point..Haematology..Treatment.Day.7..,Platelets.day.7,...,bDNA,Ferritin_ngml,Iron_mumoll,Transferrin,TSAT,PNPLA3_Add,PNPLA3_Rec,HPCT_NG,Prednisolone,D28_DTH
0,1,0,0,36.8,86.0,135.0,74.0,94.333333,110.0,92.0,...,18.110645,1325.4,9.3,57.0,63.8,0.0,0.0,0.916418,0,0
1,1,0,0,36.1,75.0,110.0,72.0,84.666667,122.0,107.0,...,5.703739,5598.0,17.4,81.0,84.6,0.0,0.0,0.261571,1,0
2,0,0,0,37.5,91.0,102.0,62.0,75.333333,74.0,218.0,...,27.647067,3675.0,19.2,78.0,97.9,0.0,0.0,0.173867,0,0
3,0,0,0,36.5,87.0,133.0,68.0,89.666667,85.0,77.0,...,5.821736,8661.0,11.7,144.0,32.2,1.0,0.0,0.146488,0,0
4,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.709972,1832.1,26.4,123.0,85.3,2.0,1.0,0.204013,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1063,1,0,0,37.1,75.0,117.0,77.0,90.333333,97.0,126.0,...,0.803096,196.2,18.0,174.0,41.0,2.0,1.0,0.486696,0,0
1064,0,0,0,36.4,84.0,126.0,81.0,96.000000,97.0,119.0,...,3.522411,1807.8,33.9,141.0,95.2,1.0,0.0,0.990790,0,0
1065,0,0,0,37.5,70.0,100.0,62.0,74.666667,119.0,366.0,...,4.197820,396.6,12.0,72.0,66.8,1.0,0.0,1.199673,1,0
1066,0,0,0,36.8,120.0,134.0,75.0,94.666667,106.0,160.0,...,NaN,352.5,17.7,129.0,54.6,0.0,0.0,0.827577,1,0
1067,1,1,0,36.4,100.0,103.0,70.0,81.000000,106.0,77.0,...,NaN,10185.0,9.9,45.0,87.9,0.0,0.0,0.000000,0,0